# Snapfile for NamePocket

# A list of devices you want to take the screenshots from
devices([
  "iPhone 17 Pro"
])

# List of languages for screenshots
languages([
  "en-US"
  # Add more languages as needed:
  # "es-ES",
  # "fr-FR",
  # "de-DE",
  # "ja-JP"
])

# The name of the scheme which contains the UI Tests
scheme("NamePocket")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# Clear previous screenshots before generating new ones
clear_previous_screenshots(true)

# Remove the '#' to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception
override_status_bar(true)

# Arguments to pass to the app on launch
# launch_arguments(["-username testuser"])

# For more information about all available options run
# fastlane action snapshot
